In [1]:
import pandas as pd
from pathlib import Path

from curation_tools.curation_tools import download_file, upload_parquet_to_bq, concatenate_parquet_files
from curation_tools.mavedb_curation_tools import process_mavedb_metadata, process_mavedb

## Download MaveDB dump

In [2]:
mavedb_dump_url = "https://zenodo.org/records/15653325/files/mavedb-dump.20250612164404.zip"
mavedb_dump_path = f"../Dump/{mavedb_dump_url.split('/')[-1]}"

In [ ]:
download_file(mavedb_dump_url, mavedb_dump_path, overwrite=False, unarchive=True)

## Convert json to flat df

In [3]:
mavedb_metadata, processed_df = process_mavedb_metadata("../Dump/mavedb-dump.20250612164404/main.json")
mavedb_metadata.head()

# uncomment to generate template for manual curation
# mavedb_metadata.to_excel('../mavedb_studies_template.xlsx', index=False)

,dataset_id,cell_barcode,data_modality,perturbation_name,perturbed_target_symbol,perturbed_target_biotype,perturbation_type_label,perturbation_type_id,timepoint,treatment_label,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,urn:mavedb:00000001-a-1,NaN,MAVE,UBE2I,UBE2I,protein_coding,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,urn:mavedb:00000001-a-2,NaN,MAVE,UBE2I,UBE2I,protein_coding,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,urn:mavedb:00000001-a-3,NaN,MAVE,UBE2I,UBE2I,protein_coding,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,urn:mavedb:00000001-a-4,NaN,MAVE,UBE2I,UBE2I,protein_coding,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,urn:mavedb:00000001-b-1,NaN,MAVE,SUMO1,SUMO1,protein_coding,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
processed_df

,index_urn1,index_urn2,index_urn3,experiment_title,experiment_shortDescription,experiment_methodText,publication_title,publication_abstract,publication_doi,publication_publicationYear,...,scoreset_title,scoreset_methodText,scoreset_numVariants,target_name,gene_category,gene_targetSequence.taxonomy.organismName,identifier_Ensembl,identifier_RefSeq,identifier_UniProt,gene_name
0,urn:mavedb:00000001,urn:mavedb:00000001-a,urn:mavedb:00000001-a-1,UBE2I yeast complementation,A Deep Mutational Scan of the human SUMO E2 co...,A Deep Mutational Scan of UBE2I using function...,A framework for exhaustively mapping functiona...,Although we now routinely sequence human genom...,10.15252/msb.20177908,2017,...,UBE2I imputed & refined,##Scoring procedure:\r\nDMS-BarSeq and DMS-Til...,3180,UBE2I,protein_coding,Homo sapiens,ENSG00000103275,NM_003345,P63279,UBE2I
1,urn:mavedb:00000001,urn:mavedb:00000001-a,urn:mavedb:00000001-a-2,UBE2I yeast complementation,A Deep Mutational Scan of the human SUMO E2 co...,A Deep Mutational Scan of UBE2I using function...,A framework for exhaustively mapping functiona...,Although we now routinely sequence human genom...,10.15252/msb.20177908,2017,...,UBE2I DMS-BarSeq,##Scoring procedure:\r\nDMS-BarSeq and reads w...,3418,UBE2I,protein_coding,Homo sapiens,ENSG00000103275,NM_003345,P63279,UBE2I
2,urn:mavedb:00000001,urn:mavedb:00000001-a,urn:mavedb:00000001-a-3,UBE2I yeast complementation,A Deep Mutational Scan of the human SUMO E2 co...,A Deep Mutational Scan of UBE2I using function...,A framework for exhaustively mapping functiona...,Although we now routinely sequence human genom...,10.15252/msb.20177908,2017,...,UBE2I DMS-TileSeq,##Scoring procedure:\r\nDMS-TileSeq reads were...,7390,UBE2I,protein_coding,Homo sapiens,ENSG00000103275,NM_003345,P63279,UBE2I
3,urn:mavedb:00000001,urn:mavedb:00000001-a,urn:mavedb:00000001-a-4,UBE2I yeast complementation,A Deep Mutational Scan of the human SUMO E2 co...,A Deep Mutational Scan of UBE2I using function...,A framework for exhaustively mapping functiona...,Although we now routinely sequence human genom...,10.15252/msb.20177908,2017,...,UBE2I joint data,##Scoring procedure:\r\nDMS-BarSeq and DMS-Til...,10438,UBE2I,protein_coding,Homo sapiens,ENSG00000103275,NM_003345,P63279,UBE2I
4,urn:mavedb:00000001,urn:mavedb:00000001-b,urn:mavedb:00000001-b-1,SUMO1 yeast complementation,A Deep Mutational Scan of the human SUMO1 usin...,A Deep Mutational Scan of SUMO1 using function...,A framework for exhaustively mapping functiona...,Although we now routinely sequence human genom...,10.15252/msb.20177908,2017,...,SUMO1 imputed and refined,##Scoring procedure:\r\nDMS-TileSeq reads were...,2020,SUMO1,protein_coding,Homo sapiens,ENSG00000116030,NM_001005781.1,P63165,SUMO1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,urn:mavedb:00001239,urn:mavedb:00001239-a,urn:mavedb:00001239-a-3,Deep mutational scanning of the human insulin ...,Deep Mutational Scanning of the Human Insulin ...,Variants were generated using nicking mutagene...,Deep mutational scanning of the human insulin ...,SummaryThe insulin receptor (INSR) entrains ti...,10.1101/2024.09.07.611782,2024,...,mAb 83-14 Binding Assay,"For this assay, cells were harvested and incub...",19100,INSR,protein_coding,Homo sapiens,NaN,NaN,NaN,INSR
1190,urn:mavedb:00001239,urn:mavedb:00001239-a,urn:mavedb:00001239-a-4,Deep mutational scanning of the human insulin ...,Deep Mutational Scanning of the Human Insulin ...,Variants were generated using nicking mutagene...,Deep mutational scanning of the human insulin ...,SummaryThe insulin receptor (INSR) entrains ti...,10.1101/2024.09.07.611782,2024,...,mAb 83-14 Stimulated Signalling,"For this assay, cells were stimulated with mAb...",19100,INSR,protein_coding,Homo sapiens,NaN,NaN,NaN,INSR
1191,urn:mavedb:00001239,urn:mavedb:00001239-a,urn:mavedb:00001239-a-5,Deep mutational scanning of the human insulin ...,Deep Mutational Scanning of the Human Insulin ...,Variants were generated using nicking mutagene...,Deep mutational scanning of the human insulin ...,SummaryThe insulin receptor (INSR) entrains ti...,10.1101/2024.09.07.611782,2024,...,mAb 83-07 Stimulated Signalling,"For this assay, cells were stimulated with mAb...",19100,INSR,protein_coding,Homo sapiens,NaN,NaN,NaN,INSR
1192,urn:mavedb:00001239,urn:mavedb:00001239-a,urn:mavedb:00001239-a-6,Deep mutational scanning of the human insulin ...,Deep Mutational Scanning of the Human Insulin ...,Variants were generated using nicking mutagene...,Deep mutational scanning of the human insulin ...,SummaryThe insulin receptor (INSR) entrains ti...,10.1101/2024.09.07.611782,2024,...,Insulin Binding Assay,"For this assay, cells were harvested and incub...",19100,INSR,protein_coding,Homo sapiens,NaN,NaN,NaN,INSR
1193,urn:mavedb:00001239,urn:mavedb:00001239-a,urn:mavedb:00001239-a-7,Deep mutational scanning of the human insulin ...,Deep Mutational Scanning of the Human Insulin ...,Variants were generated using nicking mutagene...,Deep mutational scanning of the human insulin ...,SummaryThe insulin receptor (INSR) entrains ti...,10.1101/2024.09.07.611782,2024,...,Cell Surface Expresison,"For this assay, cells were harvested and incub...",19100,INSR,protein_coding,Homo sapiens,NaN,NaN,NaN,INSR

## Read the manually curated mavedb metadata file

In [5]:
mavedb_metadata_cur = pd.read_excel("../mavedb_studies.xlsx")
# filter for curated only
mavedb_metadata_cur = mavedb_metadata_cur[mavedb_metadata_cur['is_curated'] == 'Yes']

mavedb_metadata_cur

,dataset_id,is_curated,data_modality,perturbation_name,perturbed_target_symbol,perturbed_target_biotype,perturbation_type_label,perturbation_type_id,timepoint,treatment_label,...,software_counts_id,software_counts_label,software_analysis_id,software_analysis_label,score_interpretation,reference_genome_id,reference_genome_label,associated_datasets,license_label,license_id
0,urn:mavedb:00000001-a-1,Yes,MAVE,UBE2I,UBE2I,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""urn:mavedb:00000001-a-1...",CC0 1.0,SWO:1000049
1,urn:mavedb:00000001-a-2,Yes,MAVE,UBE2I,UBE2I,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""SRP109101"",""dataset_uri...",CC0 1.0,SWO:1000049
2,urn:mavedb:00000001-a-3,Yes,MAVE,UBE2I,UBE2I,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""SRP109119"",""dataset_uri...",CC0 1.0,SWO:1000049
3,urn:mavedb:00000001-a-4,Yes,MAVE,UBE2I,UBE2I,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""urn:mavedb:00000001-a-4...",CC0 1.0,SWO:1000049
4,urn:mavedb:00000001-b-1,Yes,MAVE,SUMO1,SUMO1,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""urn:mavedb:00000001-b-1...",CC0 1.0,SWO:1000049
5,urn:mavedb:00000001-b-2,Yes,MAVE,SUMO1,SUMO1,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""urn:mavedb:00000001-b-2...",CC0 1.0,SWO:1000049
6,urn:mavedb:00000001-c-1,Yes,MAVE,CALM1,CALM1,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""urn:mavedb:00000001-c-1...",CC0 1.0,SWO:1000049
7,urn:mavedb:00000001-c-2,Yes,MAVE,CALM1,CALM1,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""urn:mavedb:00000001-c-2...",CC0 1.0,SWO:1000049
8,urn:mavedb:00000001-d-1,Yes,MAVE,TPK1,TPK1,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""urn:mavedb:00000001-d-1...",CC0 1.0,SWO:1000049
9,urn:mavedb:00000001-d-2,Yes,MAVE,TPK1,TPK1,protein_coding,DMS,NaN,P2D,NaN,...,NaN,custom,NaN,custom,0 = same as null control; 1 = synonymous,NaN,NaN,"[{""dataset_accession"":""urn:mavedb:00000001-d-2...",CC0 1.0,SWO:1000049
79,urn:mavedb:00000047-a-1,Yes,MAVE,CCR5,CCR5,protein_coding,DMS,NaN,P1D,NaN,...,NaN,Enrich,NaN,Enrich,negative values = depletion; positive values =...,NaN,NaN,"[{""dataset_accession"":""GSE100368"",""dataset_uri...",CC0 1.0,SWO:1000049
80,urn:mavedb:00000047-b-1,Yes,MAVE,CCR5,CCR5,protein_coding,DMS,NaN,P1D,NaN,...,NaN,Enrich,NaN,Enrich,negative values = depletion; positive values =...,NaN,NaN,"[{""dataset_accession"":""GSE100368"",""dataset_uri...",CC0 1.0,SWO:1000049
81,urn:mavedb:00000047-c-1,Yes,MAVE,CCR5,CCR5,protein_coding,DMS,NaN,P1D,NaN,...,NaN,Enrich,NaN,Enrich,negative values = depletion; positive values =...,NaN,NaN,"[{""dataset_accession"":""GSE100368"",""dataset_uri...",CC0 1.0,SWO:1000049
99,urn:mavedb:00000054-a-1,Yes,MAVE,PTEN,PTEN,protein_coding,DMS,NaN,P3D,NaN,...,NaN,Enrich2,NaN,Enrich2,negative values = decreased phosphatase activi...,NaN,NaN,"[{""dataset_accession"":""PRJNA437337"",""dataset_u...",NaN,NaN

## Processing of a MaveDB entry

In [ ]:
for mavedb_entry in mavedb_metadata_cur['dataset_id']:
    print(f"ℹ️ Processing: {mavedb_entry}")
    process_mavedb(
        mavedb_dataset_id=mavedb_entry,
        mavedb_csv_dir='../Dump/mavedb-dump.20250612164404/csv',
        curated_metadata_df=mavedb_metadata_cur,
        non_curated_h5ad_dir="../non_curated/h5ad",
        overwrite=False
    )

## Concatenate all parquet files and save

In [ ]:
parquet_dir = "../curated/parquet"
output_path_metadata = "../curated/mavedb_all_curated_metadata.parquet"
output_path_data = "../curated/mavedb_all_curated_data.parquet"

### Metadata

In [ ]:
concatenate_parquet_files(
    parquet_dir=parquet_dir,
    output_path=output_path_metadata,
    pattern="*_curated_metadata.parquet"
)

### Data

In [ ]:
concatenate_parquet_files(
    parquet_dir=parquet_dir,
    output_path=output_path_data,
    pattern="*_curated_data.parquet"
)

## Upload to BQ

In [ ]:
bq_dataset_id = "prj-ext-dev-pertcat-437314.mavedb"
curated_parquet_data_path = "../curated/mavedb_all_curated_data.parquet"
curated_parquet_metadata_path = "../curated/mavedb_all_curated_metadata.parquet"
bq_metadata_table_name="metadata"
bq_data_table_name="data"

### Metadata

In [ ]:
upload_parquet_to_bq(
    parquet_path=curated_parquet_metadata_path,
    bq_dataset_id=bq_dataset_id,
    bq_table_name=bq_metadata_table_name,
    key_columns=["dataset_id", "sample_id"]
)

### Data

In [ ]:
upload_parquet_to_bq(
    parquet_path=curated_parquet_data_path,
    bq_dataset_id=bq_dataset_id,
    bq_table_name=bq_data_table_name,
    key_columns=["dataset_id", "sample_id"]
)